# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mattscilipoti-rdialog}
  s.version = "0.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aleks Clark", "Matt Scilipoti"]
  s.date = %q{2009-11-03}
  s.description = %q{A gem providing a ruby interface to the n-curses dialog generator - 'dialog'.
      'Forked' from http://rubyforge.org/projects/rdialog.  
      All credit goes to its author: Aleks Clark.
      We just made small tweaks (and added jeweller support).}
  s.email = %q{matt@scilipoti.name}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mattscilipoti-rdialog.rb",
     "lib/rdialog/rdialog.rb",
     "lib/rdialog/version.rb",
     "scripts/txt2html",
     "setup.rb",
     "test/test_helper.rb",
     "test/test_rdialog.rb",
     "website/index.html",
     "website/index.txt",
     "website/javascripts/rounded_corners_lite.inc.js",
     "website/stylesheets/screen.css",
     "website/template.rhtml"
  ]
  s.homepage = %q{http://github.com/mattscilipoti/mattscilipoti-rdialog}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem providing a ruby interface to the n-curses dialog generator - 'dialog'.}
  s.test_files = [
    "test/test_rdialog.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
